import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import Ponsel from "@/components/ponsel";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Website Kerja Praktek",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Ponsel />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
