"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Website Kerja Praktek",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    if (window.innerWidth >= 768) {
      alert("website tidak bekerja pada dekstop gunakan smartphone anda");
    }
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
